title: digits
description: A sample Next.js 14 application featuring Prisma, PostgreSQL, and Bootstrap 5 React.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
